# Generated by Django 4.0.1 on 2022-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0004_remove_event_from_date_event_from_event_host_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('Contact_no', models.IntegerField()),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Event_name', models.CharField(max_length=32)),
            ],
        ),
    ]
