# Generated by Django 4.0.1 on 2022-01-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0005_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Event_name',
            field=models.CharField(choices=[('o', 'o'), ('b', 'b'), ('j', 'j'), ('e', 'e'), ('c', 'c'), ('t', 't'), ('s', 's')], max_length=32),
        ),
    ]
