# Generated by Django 4.0.1 on 2022-01-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0006_alter_participant_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Event_name',
            field=models.CharField(choices=[('Atul', 'Atul'), ('Vedant', 'Vedant'), ('Vedant', 'Vedant'), ('Falguni', 'Falguni'), ('hena', 'hena')], max_length=32),
        ),
    ]
