# Generated by Django 4.0.1 on 2022-01-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0007_alter_participant_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='No_of_people',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='Registration_Type',
            field=models.CharField(blank=True, choices=[('Group', 'Group'), ('Individual', 'Individual')], max_length=32),
        ),
    ]
