# Generated by Django 4.0.1 on 2022-01-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0008_participant_no_of_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Host_Email',
        ),
    ]
