# Generated by Django 4.0.1 on 2022-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0008_participant_no_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Email_ID',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Event_name',
            field=models.CharField(blank=True, choices=[('Atul', 'Atul'), ('Vedant', 'Vedant'), ('Vedant', 'Vedant'), ('Falguni', 'Falguni'), ('hena', 'hena')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='No_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Registration_Type',
            field=models.CharField(blank=True, choices=[('Group', 'Group'), ('Individual', 'Individual')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
