# Generated by Django 4.0.1 on 2022-01-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0009_remove_event_host_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='No_of_people',
            field=models.IntegerField(default='0'),
        ),
    ]
