# Generated by Django 4.0.1 on 2022-01-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0009_alter_participant_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='From',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Host_Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='Registration_Deadline',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='To',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Contact_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Email_ID',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Event_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='participant',
            name='No_of_people',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Registration_Type',
            field=models.CharField(blank=True, choices=[('Group', 'Group'), ('Individual', 'Individual')], max_length=32),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
