# Generated by Django 4.0.1 on 2022-01-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0010_alter_event_from_alter_event_host_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='No_of_people',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
