# Generated by Django 4.0.1 on 2022-01-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0011_event_password_alter_participant_no_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='From',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Registration_Deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='To',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
